### ISSUE TITLE
Reliability of the DVD player on Pi

### ISSUE THREAD

**Issue by cmoulliard** [chetbox/raspberry-pi-dvd-player#2]
Question

- What is the level of Reliability of the DVD player on Pi ? 
- Does it work without interruption of the streaming of the video ? 
- Do we need Pi4 ?
- Do we need licence to decode mpeg stream (see https://codecs.raspberrypi.org/mpeg-2-license-key/) ?

**Comment by chetbox** [comment]
Hi! Thanks for the questions. Glad you're considering using this. 

> - What is the level of Reliability of the DVD player on Pi ? 

I've found it to be very reliable. Just put the DVD and it plays as you would expect. I don't really have to think about it. 

> - Does it work without interruption of the streaming of the video ? 
> - Do we need Pi4 ?

Yes! The video plays smoothly on my Pi Zero thanks to hardware accelerated decoding. 

> - Do we need licence to decode mpeg stream (see https://codecs.raspberrypi.org/mpeg-2-license-key/) ?

If you're using a Pi 4 you won't need this because it's powerful enough to decode in software. You will need it I did on the Pi Zero. 

I personally like that the Pi Zero can deal with this with very low power consumption. This cheap Pi has one job and it does it well.

**Comment by cmoulliard** [comment]
> I've found it to be very reliable. Just put the DVD and it plays as you would expect. I don't really have to think about it.

As it seems that the DVD player Samsung is not available anymore (see your homepage on your github project). Is there another one that you would recommend ?

**Comment by cmoulliard** [comment]
> If you're using a Pi 4 you won't need this because it's powerful enough to decode in software. You will need it I did on the Pi Zero.

Have you been faced with problems using encrypted DVD where a region free software is needed (https://forum.kodi.tv/showthread.php?tid=274319) ?

**Comment by chetbox** [comment]
Any regular USB DVD drive should work fine.

I have not tried playing DVDs from other regions.
